/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mv_staff;



/**
 *
 * @author TEST
 */
public class executives extends javax.swing.JFrame {

    /**
     * Creates new form Login_s
     */
    public executives() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_showtimesmovies = new javax.swing.JButton();
        btn_showtimesrooms = new javax.swing.JButton();
        btn_orderstickets = new javax.swing.JButton();
        btn_transactionsorders = new javax.swing.JButton();
        btn_ticketsrooms = new javax.swing.JButton();
        btn_transactionspromotions = new javax.swing.JButton();
        btn_transactionspayments = new javax.swing.JButton();
        btn_transactionsshowtimes = new javax.swing.JButton();
        btn_transactionslocations = new javax.swing.JButton();
        btn_stafflocations = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Executives");

        btn_showtimesmovies.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        btn_showtimesmovies.setText("Showtimes-Movies");
        btn_showtimesmovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showtimesmoviesActionPerformed(evt);
            }
        });

        btn_showtimesrooms.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        btn_showtimesrooms.setText("Showtimes-Rooms");
        btn_showtimesrooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showtimesroomsActionPerformed(evt);
            }
        });

        btn_orderstickets.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        btn_orderstickets.setText("Orders-Tickets");
        btn_orderstickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ordersticketsActionPerformed(evt);
            }
        });

        btn_transactionsorders.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        btn_transactionsorders.setText("Transactions-Orders");
        btn_transactionsorders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transactionsordersActionPerformed(evt);
            }
        });

        btn_ticketsrooms.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        btn_ticketsrooms.setText("Tickets-Rooms");
        btn_ticketsrooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ticketsroomsActionPerformed(evt);
            }
        });

        btn_transactionspromotions.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        btn_transactionspromotions.setText("Transactions-Promotions");
        btn_transactionspromotions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transactionspromotionsActionPerformed(evt);
            }
        });

        btn_transactionspayments.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        btn_transactionspayments.setText("Transactions-Payments");
        btn_transactionspayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transactionspaymentsActionPerformed(evt);
            }
        });

        btn_transactionsshowtimes.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        btn_transactionsshowtimes.setText("Transactions-Showtimes");
        btn_transactionsshowtimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transactionsshowtimesActionPerformed(evt);
            }
        });

        btn_transactionslocations.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        btn_transactionslocations.setText("Transactions-Locations");
        btn_transactionslocations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transactionslocationsActionPerformed(evt);
            }
        });

        btn_stafflocations.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        btn_stafflocations.setText("Staff-Locations");
        btn_stafflocations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stafflocationsActionPerformed(evt);
            }
        });

        btn_back.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_back.setText("Back to Main Menu");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_back)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(766, 766, 766))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_transactionsshowtimes)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_transactionspayments)
                            .addComponent(btn_ticketsrooms)
                            .addComponent(btn_transactionslocations))
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_transactionsorders)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_showtimesrooms))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_orderstickets)
                                    .addComponent(btn_transactionspromotions))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_stafflocations)
                                    .addComponent(btn_showtimesmovies))))
                        .addGap(107, 107, 107))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(136, 136, 136)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_transactionspayments)
                    .addComponent(btn_orderstickets)
                    .addComponent(btn_stafflocations))
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ticketsrooms)
                    .addComponent(btn_transactionspromotions)
                    .addComponent(btn_showtimesmovies))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btn_transactionslocations))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_transactionsorders)
                            .addComponent(btn_showtimesrooms))))
                .addGap(66, 66, 66)
                .addComponent(btn_transactionsshowtimes)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_stafflocationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stafflocationsActionPerformed
        join_staff_locations.staff_locations_query Info = new join_staff_locations.staff_locations_query();
        Info.setVisible(true);      
    }//GEN-LAST:event_btn_stafflocationsActionPerformed

    private void btn_showtimesmoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showtimesmoviesActionPerformed
        join_shotimes_movies.showtimes_movies_query Info = new join_shotimes_movies.showtimes_movies_query();
        Info.setVisible(true);
    }//GEN-LAST:event_btn_showtimesmoviesActionPerformed

    private void btn_showtimesroomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showtimesroomsActionPerformed
        join_showtimes_room.showtimes_room_query Info = new join_showtimes_room.showtimes_room_query();
        Info.setVisible(true);
    }//GEN-LAST:event_btn_showtimesroomsActionPerformed

    private void btn_transactionslocationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transactionslocationsActionPerformed
        join_transactions_locations.transactions_locations_query Info = new join_transactions_locations.transactions_locations_query();
        Info.setVisible(true);
    }//GEN-LAST:event_btn_transactionslocationsActionPerformed

    private void btn_ordersticketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ordersticketsActionPerformed
        join_orders_tickets.orders_tickets_query Info = new join_orders_tickets.orders_tickets_query();
        Info.setVisible(true);
    }//GEN-LAST:event_btn_ordersticketsActionPerformed

    private void btn_transactionsordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transactionsordersActionPerformed
        join_transactions_orders.transactions_orders_query Info = new join_transactions_orders.transactions_orders_query();
        Info.setVisible(true);
    }//GEN-LAST:event_btn_transactionsordersActionPerformed

    private void btn_ticketsroomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ticketsroomsActionPerformed
        join_tickets_room.tickets_room_query Info = new join_tickets_room.tickets_room_query();
        Info.setVisible(true);
    }//GEN-LAST:event_btn_ticketsroomsActionPerformed

    private void btn_transactionspromotionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transactionspromotionsActionPerformed
        join_transactions_promotions.transactions_promotions_query Info = new join_transactions_promotions.transactions_promotions_query();
        Info.setVisible(true);
    }//GEN-LAST:event_btn_transactionspromotionsActionPerformed

    private void btn_transactionspaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transactionspaymentsActionPerformed
        join_transactions_payments.transactions_payments_query Info = new join_transactions_payments.transactions_payments_query();
        Info.setVisible(true);
    }//GEN-LAST:event_btn_transactionspaymentsActionPerformed

    private void btn_transactionsshowtimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transactionsshowtimesActionPerformed
        join_transactions_showtimes.transactions_showtimes_query Info = new join_transactions_showtimes.transactions_showtimes_query();
        Info.setVisible(true);
    }//GEN-LAST:event_btn_transactionsshowtimesActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        mv_login.welcome_mv Info = new mv_login.welcome_mv();
        Info.setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(executives.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(executives.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(executives.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(executives.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new executives().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_orderstickets;
    private javax.swing.JButton btn_showtimesmovies;
    private javax.swing.JButton btn_showtimesrooms;
    private javax.swing.JButton btn_stafflocations;
    private javax.swing.JButton btn_ticketsrooms;
    private javax.swing.JButton btn_transactionslocations;
    private javax.swing.JButton btn_transactionsorders;
    private javax.swing.JButton btn_transactionspayments;
    private javax.swing.JButton btn_transactionspromotions;
    private javax.swing.JButton btn_transactionsshowtimes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
